// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txeyvnhraorruszptskw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZXl2bmhyYW9ycnVzenB0c2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNDE4MzYsImV4cCI6MjA0OTkxNzgzNn0.nm1ioTv9vUNhjuV3JJ0_Au9tjd-1_S-TER2hI_ygZao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);